### ISSUE TITLE
wrong datatype in Atomable.hs:56:11, class method toAddTypeExpr

### ISSUE THREAD

**Issue by testexplode** [agentm/project-m36#167]
Currently project-M36 does not compile for me, the 'master' branch and the version with tag v0.3.
I'm using ghc 8.2.1 and 
cabal-install version 2.0.0.0
compiled using version 2.0.0.2 of the Cabal library

The compile statement is: 
     cabal new-build --allow-newer=distributed-process
The platform is manjaro-linux.

The error message is:

    src/lib/ProjectM36/Atomable.hs:56:11: error:
        • The default type signature for toAddTypeExpr:
            forall (proxy :: * -> *).
            (Generic a, AtomableG (Rep a)) =>
            proxy a -> DatabaseContextExpr
          does not match its corresponding non-default type signature
        • When checking the class method:
            toAddTypeExpr :: forall a.
                             Atomable a =>
                             Proxy a -> DatabaseContextExpr
          In the class declaration for ‘Atomable’
       |
    56 |   default toAddTypeExpr :: (Generic a, AtomableG (Rep a)) => proxy a -> DatabaseContextExpr
       |           ^^^^^^^^^^^^^

**Comment by agentm** [comment]
Hi @testexplode! 

Sorry that it's not more obvious, but GHC 8.2 support is in branch "support_ghc_8.2". I am hesitant to merge this to master until some package version (out of my control) are adjusted. The newer package also changed some APIs, so there's a chicken-and-egg problem here.

I just tested a build on the "support_ghc_8.2" branch so it should be working just fine. Let me know if you encounter further trouble.

**Comment by agentm** [comment]
Also, let me know if there is any use/demand for static binaries. I can see how downloading and compiling with GHC might be daunting for someone who just wants to try TutorialD.

**Comment by testexplode** [comment]
Now the linking makes problems:

```
[user@computer ~/programming/M36/project-m36]$ cabal new-build --allow-newer=distributed-process
In order, the following will be built (use -v for more details):
 - project-m36-0.3 (exe:Example-Blog) (first run)
 - project-m36-0.3 (exe:Example-Hair) (first run)
 - project-m36-0.3 (exe:Example-OutOfTheTarpit) (first run)
 - project-m36-0.3 (exe:Example-SimpleClient) (first run)
 - project-m36-0.3 (exe:bigrel) (first run)
 - project-m36-0.3 (exe:handles) (first run)
 - project-m36-0.3 (exe:project-m36-server) (first run)
 - project-m36-0.3 (exe:project-m36-websocket-server) (first run)
 - project-m36-0.3 (exe:tutd) (first run)
Preprocessing executable 'Example-Blog' for project-m36-0.3..
Building executable 'Example-Blog' for project-m36-0.3..
Preprocessing executable 'Example-SimpleClient' for project-m36-0.3..
Building executable 'Example-SimpleClient' for project-m36-0.3..
Preprocessing executable 'Example-Hair' for project-m36-0.3..
Building executable 'Example-Hair' for project-m36-0.3..
Preprocessing executable 'Example-OutOfTheTarpit' for project-m36-0.3..
Building executable 'Example-OutOfTheTarpit' for project-m36-0.3..
Linking /home/user/programming/M36/project-m36/dist-newstyle/build/x86_64-linux/ghc-8.2.1/project-m36-0.3/c/Example-SimpleClient/build/Example-SimpleClient/Example-SimpleClient ...
Linking /home/user/programming/M36/project-m36/dist-newstyle/build/x86_64-linux/ghc-8.2.1/project-m36-0.3/c/Example-Hair/build/Example-Hair/Example-Hair ...
Linking /home/user/programming/M36/project-m36/dist-newstyle/build/x86_64-linux/ghc-8.2.1/project-m36-0.3/c/Example-OutOfTheTarpit/build/Example-OutOfTheTarpit/Example-OutOfTheTarpit ...
Linking /home/user/programming/M36/project-m36/dist-newstyle/build/x86_64-linux/ghc-8.2.1/project-m36-0.3/c/Example-Blog/build/Example-Blog/Example-Blog ...
/usr/lib/ghc-8.2.1/ghc-8.2.1/libHSghc-8.2.1.a(Terminal.o):s5Ac_info: error: undefined reference to 'set_curterm'
/usr/lib/ghc-8.2.1/ghc-8.2.1/libHSghc-8.2.1.a(Terminal.o):s5Ac_info: error: undefined reference to 'set_curterm'
/usr/lib/ghc-8.2.1/ghc-8.2.1/libHSghc-8.2.1.a(Terminal.o):s5Ac_info: error: undefined reference to 'set_curterm'
/usr/lib/ghc-8.2.1/terminfo-0.4.1.0/libHSterminfo-0.4.1.0.a(Base.o):r9DX_info: error: undefined reference to 'tigetnum'
/usr/lib/ghc-8.2.1/terminfo-0.4.1.0/libHSterminfo-0.4.1.0.a(Base.o):s9PJ_info: error: undefined reference to 'set_curterm'
/usr/lib/ghc-8.2.1/terminfo-0.4.1.0/libHSterminfo-0.4.1.0.a(Base.o):s9PJ_info: error: undefined reference to 'del_curterm'
/usr/lib/ghc-8.2.1/terminfo-0.4.1.0/libHSterminfo-0.4.1.0.a(Base.o):s9PJ_info: error: undefined reference to 'setupterm'
collect2: fout: ld gaf exit-status 1 terug

```
I want to use the library and inspect the code and have the haddock-documentation, so I prefer to compile the module by myself.
But with this cutting-edge Arch-linux it is hard, perhaps it would be with ubuntu simpler, because it uses the old stable ghc-compiler.

**Comment by testexplode** [comment]
Now it works!
It was a local problem here. I uninstalled the system libraries and reinstlled them, also reinstalled the Arch-Linux packet "ghc-pristine", which makes static libraries, compiled the packets terminfo and haskeline newly (--reinstall) then it worked.

At the end, it was hard to find the executables. They are at
/home/user/programming/M36/project-m36/dist-newstyle/build/x86_64-linux/ghc-8.2.1/project-m36-0.3/c/tutd/build/tutd/

Thank you for pointing me to the right branch.

**Comment by agentm** [comment]
Great! Sorry about the GHC 8.2 incompatibility for now. 

We can't offer an estimate for when we will support GHC 8.2 in the master branch because we are waiting on other modules- the pull requests are in- but we certainly want it as soon as possible.

Please do continue to open tickets for any issues you encounter.

**Comment by testexplode** [comment]
Now it builds the executables.
But now is the question: How can I use the library and its dependencies globally?
With ``cabal new-build`` the executables are build seperately from the rest.

Is there a possibility, or have I to wait until I do not need anymore the ``--allow-newer=distributed-process`` which to my knowledge works only with the command ``cabal new-build``, not with ``cabal install `` ?

**Comment by agentm** [comment]
Hi @testexplode,

Since you can't build from the hackage version due to GHC 8.2 support currently lacking in a dependency of project-m36, take a look at `cabal` or `stack` features which allow building a project against a git repo or a local filesystem:

* [stack local clone](https://stackoverflow.com/questions/32849269/how-to-install-use-a-local-version-of-package-using-stack#32852774)
* [stack reference to git repo](https://docs.haskellstack.org/en/stable/yaml_configuration/#complex-package-locations-location)
* [cabal add-source](https://www.haskell.org/cabal/users-guide/installing-packages.html#sandboxes-basic-usage)

**Comment by agentm** [comment]
@testexplode, were you able to build against a project-m36 git working tree?

GHC 8.2 support is covered in #121, so I will cover 8.2 issues there.
